name: Reporting V2 Performance Testing

on:
  push:

jobs:
  update-reporting-v2:
    uses: ./.github/workflows/configure-kingdom.yml
    secrets: inherit
    with:
      image-tag: a037c3de037d7963aa64fda45929f4056868212f
      environment: dev
      apply: true
