name: Reporting V2 Performance Testing

on:
  workflow_dispatch:

jobs:
  update-reporting-v2:
    uses: ./.github/workflows/configure-reporting-v2.yml
    secrets: inherit
    with:
      image-tag: a037c3de037d7963aa64fda45929f4056868212f
      environment: dev
      apply: true
